- name: Test if folder exist
  stat:
    path={{ phpstorm_dir }}
  register: phpstorm_exist

- name: Download phpStorm archive
  get_url:
    url=http://download.jetbrains.com/webide/PhpStorm-{{ phpstorm_version }}.tar.gz
    dest={{ phpstorm_archive }}
  when: phpstorm_exist.stat.exists == False

- name: Decompress phpStorm archive
  unarchive:
    src={{ phpstorm_archive }}
    dest={{ phpstorm_install_dir }}
    copy=no
  when: phpstorm_exist.stat.exists == False

- name: Move phpStorm folder
  shell:
    mv {{ phpstorm_install_dir }}/PhpStorm-* {{ phpstorm_dir }}
    creates="{{ phpstorm_dir }}"

- name: Create symlink
  file:
    src={{ phpstorm_dir }}/bin/phpstorm.sh
    dest={{ phpstorm_bin }}
    state=link

- name: Remove phpStorm archive
  file:
    path={{ phpstorm_archive }}
    state=absent

- name: Get stat of phpstorm
  stat:
    path="{{ phpstorm_bin }}"
  register: phpstorm_stat

- name: Test if phpstorm is executable
  fail:
    msg="{{ phpstorm_bin }} isn't executable"
  when: phpstorm_stat.stat.xgrp != true